/**
 * ForgeComply 360 Reporter - Word (DOCX) Export Utility
 * Generates an editable SSP document in DOCX format for federal customers.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  Footer,
  PageNumber,
  Header,
} from 'docx';
import type { SSPData } from '../types';
import { SECTIONS } from '../config/sections';

// Brand colors (matching ForgeComply 360)
const NAVY = '1a2744';
const WHITE = 'FFFFFF';

interface DocxOptions {
  data: SSPData;
  progress: Record<string, number>;
}

/**
 * Generate SSP DOCX document
 */
export async function generateDOCX(options: DocxOptions): Promise<Blob> {
  const { data, progress } = options;

  const children: Paragraph[] = [];

  // ============================================
  // COVER PAGE
  // ============================================
  children.push(new Paragraph({ spacing: { before: 4000 } }));
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: 'System Security Plan',
          bold: true,
          size: 56,
          color: NAVY,
          font: 'Calibri',
        }),
      ],
    })
  );
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: 'FISMA / FedRAMP Authorization Package',
          size: 24,
          color: '64748b',
          font: 'Calibri',
        }),
      ],
    })
  );

  children.push(new Paragraph({ spacing: { before: 600 } }));

  // System info table on cover
  const coverFields = [
    ['System Name', data.sysName || 'Untitled System'],
    ['System Acronym', data.sysAcronym || 'N/A'],
    ['Owning Agency', data.owningAgency || 'Not specified'],
    ['Authorization Type', data.authType || 'Not specified'],
    ['Impact Level', getOverallImpact(data) || 'Not categorized'],
    ['Control Baseline', data.ctrlBaseline || 'Not selected'],
  ];

  children.push(buildInfoTable(coverFields));
  children.push(new Paragraph({ spacing: { before: 600 } }));

  // Completion status
  const overallCompletion = Math.round(
    Object.values(progress).reduce((a, b) => a + b, 0) /
      (Object.keys(progress).length || 1)
  );
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `SSP Completion: ${overallCompletion}%`,
          bold: true,
          size: 22,
          color: NAVY,
        }),
      ],
    })
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2000 },
      children: [
        new TextRun({
          text: `Generated by ForgeComply 360 Reporter on ${new Date().toLocaleDateString()}`,
          size: 18,
          color: '94a3b8',
          italics: true,
        }),
      ],
    })
  );

  // Page break after cover
  children.push(new Paragraph({ pageBreakBefore: true }));

  // ============================================
  // TABLE OF CONTENTS PLACEHOLDER
  // ============================================
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: 'Table of Contents', bold: true, color: NAVY })],
    })
  );
  children.push(
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: 'To generate the table of contents in Word, right-click below and select "Update Field", or press Ctrl+A then F9.',
          italics: true,
          color: '64748b',
          size: 20,
        }),
      ],
    })
  );

  // Group sections
  const groups: Record<string, typeof SECTIONS> = {};
  SECTIONS.forEach((section) => {
    if (!groups[section.grp]) groups[section.grp] = [];
    groups[section.grp].push(section);
  });

  let sectionNum = 1;
  Object.entries(groups).forEach(([groupName, sections]) => {
    children.push(
      new Paragraph({
        spacing: { before: 200 },
        children: [
          new TextRun({
            text: groupName.toUpperCase(),
            bold: true,
            size: 20,
            color: NAVY,
          }),
        ],
      })
    );
    sections.forEach((section) => {
      const completion = progress[section.id] || 0;
      children.push(
        new Paragraph({
          indent: { left: 360 },
          children: [
            new TextRun({ text: `${sectionNum}. ${section.label}`, size: 20 }),
            new TextRun({ text: `   ${Math.round(completion)}%`, size: 20, color: completion >= 100 ? '22c55e' : '64748b' }),
          ],
        })
      );
      sectionNum++;
    });
  });

  // ============================================
  // SECTION PAGES
  // ============================================
  sectionNum = 1;
  SECTIONS.forEach((section) => {
    // Page break before each section
    children.push(new Paragraph({ pageBreakBefore: true }));

    // Section heading
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({
            text: `${sectionNum}. ${section.label}`,
            bold: true,
            color: NAVY,
          }),
        ],
      })
    );

    if (section.ref) {
      children.push(
        new Paragraph({
          spacing: { after: 200 },
          children: [
            new TextRun({
              text: section.ref,
              size: 18,
              color: '94a3b8',
              italics: true,
            }),
          ],
        })
      );
    }

    // Section content
    const sectionParagraphs = renderSectionContent(section.id, data);
    children.push(...sectionParagraphs);

    sectionNum++;
  });

  // Build document
  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
        heading1: {
          run: { font: 'Calibri', size: 32, bold: true, color: NAVY },
          paragraph: { spacing: { before: 240, after: 120 } },
        },
        heading2: {
          run: { font: 'Calibri', size: 26, bold: true, color: NAVY },
          paragraph: { spacing: { before: 200, after: 100 } },
        },
      },
    },
    sections: [
      {
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: `SSP — ${data.sysName || 'System Security Plan'}`,
                    size: 16,
                    color: '94a3b8',
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: 'Page ', size: 16, color: '94a3b8' }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94a3b8' }),
                  new TextRun({ text: ' — ForgeComply 360 Reporter', size: 16, color: '94a3b8' }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBlob(doc);
}

// ============================================
// HELPERS
// ============================================

function getOverallImpact(data: SSPData): string {
  const levels = [data.conf, data.integ, data.avail].filter(Boolean);
  if (levels.length === 0) return '';
  if (levels.includes('High')) return 'High';
  if (levels.includes('Moderate')) return 'Moderate';
  return 'Low';
}

function buildInfoTable(rows: string[][]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: { size: 30, type: WidthType.PERCENTAGE },
              shading: { fill: NAVY },
              children: [
                new Paragraph({
                  children: [new TextRun({ text: label, bold: true, color: WHITE, size: 20 })],
                }),
              ],
            }),
            new TableCell({
              width: { size: 70, type: WidthType.PERCENTAGE },
              children: [
                new Paragraph({
                  children: [new TextRun({ text: value, size: 20 })],
                }),
              ],
            }),
          ],
        })
    ),
  });
}

function fieldParagraph(label: string, value: string | undefined): Paragraph {
  return new Paragraph({
    spacing: { after: 80 },
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 22 }),
      new TextRun({ text: value || 'Not provided', size: 22, color: value ? '000000' : '94a3b8' }),
    ],
  });
}

function textBlockParagraphs(label: string, value: string | undefined): Paragraph[] {
  const result: Paragraph[] = [
    new Paragraph({
      spacing: { before: 120 },
      children: [new TextRun({ text: label, bold: true, size: 22 })],
    }),
  ];
  if (value) {
    value.split('\n').forEach((line) => {
      result.push(
        new Paragraph({
          spacing: { after: 40 },
          children: [new TextRun({ text: line, size: 22 })],
        })
      );
    });
  } else {
    result.push(
      new Paragraph({
        children: [new TextRun({ text: 'Not provided', italics: true, color: '94a3b8', size: 22 })],
      })
    );
  }
  return result;
}

function tableFromRows(headers: string[], rows: string[][]): Table {
  const headerRow = new TableRow({
    tableHeader: true,
    children: headers.map(
      (h) =>
        new TableCell({
          shading: { fill: NAVY },
          children: [
            new Paragraph({
              children: [new TextRun({ text: h, bold: true, color: WHITE, size: 18 })],
            }),
          ],
        })
    ),
  });

  const noBorder = { style: BorderStyle.SINGLE, size: 1, color: 'e2e8f0' };
  const borders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

  const dataRows = rows.map(
    (cells) =>
      new TableRow({
        children: cells.map(
          (c) =>
            new TableCell({
              borders,
              children: [new Paragraph({ children: [new TextRun({ text: c || '', size: 18 })] })],
            })
        ),
      })
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...dataRows],
  });
}

/**
 * Render section-specific content as DOCX paragraphs
 */
function renderSectionContent(sectionId: string, data: SSPData): Paragraph[] {
  const result: Paragraph[] = [];

  const field = (label: string, value: string | undefined) => {
    result.push(fieldParagraph(label, value));
  };

  const textBlock = (label: string, value: string | undefined) => {
    result.push(...textBlockParagraphs(label, value));
  };

  switch (sectionId) {
    case 'sysinfo':
      field('System Name', data.sysName);
      field('System Acronym', data.sysAcronym);
      field('FISMA ID', data.fismaId);
      field('FedRAMP ID', data.fedrampId);
      field('Owning Agency', data.owningAgency);
      field('Agency Component', data.agencyComp);
      field('Cloud Model', data.cloudModel);
      field('Deployment Model', data.deployModel);
      field('Authorization Type', data.authType);
      field('Operational Date', data.opDate);
      textBlock('System Description', data.sysDesc);
      break;

    case 'fips199':
      field('Confidentiality', data.conf);
      field('Integrity', data.integ);
      field('Availability', data.avail);
      field('Overall Impact Level', getOverallImpact(data));
      textBlock('Categorization Justification', data.catJust);
      break;

    case 'infotypes':
      if (data.infoTypes?.length) {
        const rows = data.infoTypes.map((t) => [t.nistId || '', t.name || '', t.c || '', t.i || '', t.a || '']);
        result.push(new Paragraph({ spacing: { before: 120 } }));
        // Embed table directly into section children
        addTable(result, ['NIST ID', 'Type', 'Conf.', 'Integ.', 'Avail.'], rows);
      } else {
        field('Information Types', undefined);
      }
      textBlock('Justification', data.infoTypeJust);
      break;

    case 'baseline':
      field('Selected Baseline', data.ctrlBaseline);
      field('Tailoring Applied', data.tailoring);
      textBlock('Baseline Justification', data.baseJust);
      break;

    case 'rmf':
      field('Current RMF Step', data.rmfCurrentStep);
      field('Target ATO Date', data.rmfTargetAto);
      break;

    case 'boundary':
      textBlock('Boundary Narrative', data.bndNarr);
      if (data.bndComps?.length) {
        addTable(result, ['Component', 'Type', 'Zone'],
          data.bndComps.map((c) => [c.name || '', c.type || '', c.zone || '']));
      }
      break;

    case 'dataflow':
      textBlock('Data Flow Narrative', data.dfNarr);
      field('Encryption at Rest', data.encRest);
      field('Encryption in Transit', data.encTransit);
      field('Key Management', data.keyMgmt);
      field('Data Disposal', data.dataDisposal);
      break;

    case 'network':
      textBlock('Network Narrative', data.netNarr);
      field('Primary Data Center', data.primaryDC);
      field('Secondary/DR Data Center', data.secondaryDC);
      break;

    case 'pps':
      if (data.ppsRows?.length) {
        addTable(result, ['Port', 'Protocol', 'Service', 'Purpose', 'Direction'],
          data.ppsRows.map((r) => [r.port || '', r.proto || '', r.svc || '', r.purpose || '', r.dir || '']));
      } else {
        field('Ports, Protocols & Services', undefined);
      }
      break;

    case 'intercon':
      if (data.icRows?.length) {
        addTable(result, ['System', 'Organization', 'Type', 'Direction'],
          data.icRows.map((r) => [r.system || '', r.org || '', r.type || '', r.dir || '']));
      } else {
        field('Interconnections', undefined);
      }
      textBlock('Interconnection Notes', data.icNotes);
      break;

    case 'crypto':
      textBlock('Cryptography Narrative', data.cryptoNarr);
      if (data.cryptoMods?.length) {
        addTable(result, ['Module', 'Certificate', 'FIPS Level', 'Usage'],
          data.cryptoMods.map((m) => [m.mod || '', m.cert || '', m.level || '', m.usage || '']));
      }
      break;

    case 'personnel':
      field('System Owner', data.soName);
      field('SO Email', data.soEmail);
      field('Authorizing Official', data.aoName);
      field('AO Email', data.aoEmail);
      field('ISSO', data.issoName);
      field('ISSO Email', data.issoEmail);
      field('ISSM', data.issmName);
      field('ISSM Email', data.issmEmail);
      field('SCA', data.scaName);
      field('SCA Email', data.scaEmail);
      field('Privacy Officer', data.poName);
      field('PO Email', data.poEmail);
      break;

    case 'identity':
      field('Identity Assurance Level (IAL)', data.ial);
      field('Authenticator Assurance Level (AAL)', data.aal);
      field('Federation Assurance Level (FAL)', data.fal);
      field('MFA Methods', data.mfaMethods);
      textBlock('Identity Narrative', data.idNarr);
      break;

    case 'sepduty':
      field('Dual Control Requirements', data.dualControl);
      field('Privileged Access Management', data.privAccess);
      if (data.sepDutyMatrix?.length) {
        addTable(result, ['Role', 'Access', 'Prohibited Actions'],
          data.sepDutyMatrix.map((r) => [r.role || '', r.access || '', r.prohibited || '']));
      }
      break;

    case 'controls':
      if (data.ctrlData && Object.keys(data.ctrlData).length > 0) {
        const ctrlRows = Object.entries(data.ctrlData)
          .filter(([, v]) => v.status || v.implementation)
          .slice(0, 50) // Limit to first 50 for document size
          .map(([id, v]) => [id, v.status || '', (v.implementation || '').slice(0, 200)]);
        addTable(result, ['Control ID', 'Status', 'Implementation'], ctrlRows);
        if (Object.keys(data.ctrlData).length > 50) {
          result.push(new Paragraph({
            children: [new TextRun({ text: `... and ${Object.keys(data.ctrlData).length - 50} more controls`, italics: true, color: '94a3b8' })],
          }));
        }
      } else {
        field('Security Controls', undefined);
      }
      break;

    case 'policies':
      if (data.policyDocs?.length) {
        addTable(result, ['Control Family', 'Policy Title', 'Version', 'Status'],
          data.policyDocs.map((p) => [p.family || '', p.title || '', p.version || '', p.status || '']));
      } else {
        field('Security Policies', undefined);
      }
      break;

    case 'scrm':
      textBlock('SCRM Plan', data.scrmPlan);
      field('SBOM Format', data.sbomFormat);
      field('Provenance Tracking', data.provenance);
      if (data.scrmSuppliers?.length) {
        addTable(result, ['Supplier', 'Type', 'Criticality', 'Risk Level'],
          data.scrmSuppliers.map((s) => [s.supplier || '', s.type || '', s.criticality || '', s.riskLevel || '']));
      }
      break;

    case 'privacy':
      field('System Collects PII?', data.ptaCollectsPii);
      field('PII Types', data.ptaPiiTypes);
      field('Approximate Record Count', data.ptaRecordCount);
      field('PIA Required?', data.ptaPiaRequired);
      field('SORN Status', data.sornStatus);
      field('SORN Number', data.sornNumber);
      break;

    case 'conplan':
      textBlock('CP Purpose', data.cpPurpose);
      textBlock('CP Scope', data.cpScope);
      field('Recovery Time Objective (RTO)', data.rto);
      field('Recovery Point Objective (RPO)', data.rpo);
      field('Maximum Tolerable Downtime', data.mtd);
      field('Backup Frequency', data.backupFreq);
      field('Last CP Test Date', data.cpTestDate);
      field('CP Test Type', data.cpTestType);
      break;

    case 'irplan':
      textBlock('IR Purpose', data.irPurpose);
      textBlock('IR Scope', data.irScope);
      field('US-CERT Notification Time', data.certTime);
      field('Last IR Test Date', data.irTestDate);
      break;

    case 'cmplan':
      textBlock('CM Purpose', data.cmPurpose);
      textBlock('Change Control Process', data.cmChangeNarr);
      if (data.cmBaselines?.length) {
        addTable(result, ['Component', 'Benchmark', 'Version', 'Compliance %'],
          data.cmBaselines.map((b) => [b.comp || '', b.bench || '', b.ver || '', b.pct || '']));
      }
      break;

    case 'conmon':
      field('ISCM Strategy Type', data.iscmType);
      field('Control Assessment Rotation', data.ctrlRotation);
      textBlock('ISCM Narrative', data.iscmNarrative);
      field('Significant Change Criteria', data.sigChangeCriteria);
      field('ATO Expiry Date', data.atoExpiry);
      field('Next Assessment Date', data.nextAssessment);
      break;

    case 'poam':
      field('Review Frequency', data.poamFreq);
      textBlock('Remediation Workflow', data.poamWf);
      if (data.poamRows?.length) {
        addTable(result, ['ID', 'Weakness', 'Severity', 'Control', 'Status', 'Due'],
          data.poamRows.map((r) => [r.id || '', r.weakness || '', r.sev || '', r.ctrl || '', r.status || '', r.due || '']));
      }
      break;

    default:
      result.push(
        new Paragraph({
          children: [
            new TextRun({
              text: 'Section content pending.',
              italics: true,
              color: '94a3b8',
            }),
          ],
        })
      );
      break;
  }

  return result;
}

/**
 * Helper: push a table into the result paragraphs array.
 * Tables in docx must be section-level children — we work around the Paragraph[]
 * constraint by adding a placeholder. The caller collects these as section children.
 */
function addTable(into: Paragraph[], headers: string[], rows: string[][]) {
  // The `docx` library allows Tables as direct section children alongside Paragraphs.
  // We cast here because our intermediate array is typed Paragraph[] but the final
  // section.children accepts (Paragraph | Table)[].
  (into as unknown as (Paragraph | Table)[]).push(tableFromRows(headers, rows));
}

/**
 * Download DOCX to user's device
 */
export function downloadDOCX(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
